# Generated by Django 5.2.6 on 2025-09-26 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0002_vehiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenDeReparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrada', models.DateTimeField(auto_now_add=True)),
                ('problema', models.TextField()),
                ('estado', models.CharField(choices=[('Recibido', 'Recibido'), ('En Diagnostico', 'En Diagnóstico'), ('Esperando Piezas', 'Esperando Piezas'), ('En Reparacion', 'En Reparación'), ('Listo para Recoger', 'Listo para Recoger'), ('Entregado', 'Entregado')], default='Recibido', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.cliente')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.vehiculo')),
            ],
        ),
    ]
