# Generated by Django 5.2.6 on 2025-09-26 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0003_ordendereparacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('categoria', models.CharField(choices=[('Repuestos', 'Repuestos'), ('Sueldos', 'Sueldos'), ('Herramientas', 'Herramientas'), ('Suministros', 'Suministros'), ('Otros', 'Otros')], max_length=20)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.CharField(max_length=255)),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taller.vehiculo')),
            ],
        ),
    ]
