# Generated by Django 5.2.6 on 2025-09-28 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0005_empleado_gasto_empleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('categoria', models.CharField(choices=[('Taller', 'Pago de Cliente (Taller)'), ('Grua', 'Servicio de Grúa'), ('Otros', 'Otros Ingresos')], max_length=20)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.CharField(max_length=255)),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taller.ordendereparacion')),
            ],
        ),
    ]
