# Generated by Django 5.2.6 on 2025-09-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0006_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='kilometraje',
            field=models.IntegerField(default=0),
        ),
    ]
