# Generated by Django 5.2.6 on 2025-09-28 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0007_vehiculo_kilometraje'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('total_mano_obra', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_repuestos', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_final', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='taller.ordendereparacion')),
            ],
        ),
    ]
