# Generated by Django 5.2.6 on 2025-09-28 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0008_factura'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoConsumible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('unidad_medida', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CompraConsumible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateField()),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coste_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coste_por_unidad', models.DecimalField(decimal_places=4, editable=False, max_digits=10)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.tipoconsumible')),
            ],
        ),
    ]
