# Generated by Django 5.2.6 on 2025-09-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0010_alter_gasto_categoria_alter_gasto_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='categoria',
            field=models.CharField(choices=[('Repuestos', 'Repuestos'), ('Sueldos', 'Sueldos'), ('Herramientas', 'Herramientas'), ('Suministros', 'Suministros'), ('Otros', 'Otros'), ('Compra de Consumibles', 'Compra de Consumibles')], max_length=30),
        ),
    ]
