# Generated by Django 5.2.6 on 2025-09-28 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0011_alter_gasto_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsoConsumible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_usada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_uso', models.DateField(auto_now_add=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.ordendereparacion')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.tipoconsumible')),
            ],
        ),
    ]
