# Generated by Django 5.2.6 on 2025-09-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0012_usoconsumible'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='descripcion_mano_obra',
            field=models.TextField(blank=True, null=True),
        ),
    ]
