# Generated by Django 5.2.6 on 2025-09-28 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0013_factura_descripcion_mano_obra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='descripcion_mano_obra',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='total_mano_obra',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='total_repuestos',
        ),
        migrations.AddField(
            model_name='factura',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='LineaFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Repuesto', 'Repuesto'), ('Consumible', 'Consumible'), ('Externo', 'Trabajo Externo'), ('Mano de Obra', 'Mano de Obra')], max_length=20)),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='taller.factura')),
            ],
        ),
    ]
