# Generated by Django 5.2.6 on 2025-09-29 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0014_remove_factura_descripcion_mano_obra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='categoria',
            field=models.CharField(choices=[('Taller', 'Pago de Cliente (Taller)'), ('Grua', 'Servicio de Grúa'), ('Otros', 'Otros Ingresos'), ('Otras Ganancias', 'Otras Ganancias')], max_length=30),
        ),
    ]
