# Generated by Django 5.2.6 on 2025-09-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0015_alter_ingreso_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='categoria',
            field=models.CharField(choices=[('Taller', 'Pago de Cliente (Taller)'), ('Grua', 'Servicio de Grúa'), ('Otras Ganancias', 'Otras Ganancias'), ('Otros', 'Otros Ingresos')], max_length=30),
        ),
    ]
