# Generated by Django 5.2.6 on 2025-09-29 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0016_alter_ingreso_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='fotos_vehiculos/')),
                ('descripcion', models.CharField(max_length=50)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='taller.ordendereparacion')),
            ],
        ),
    ]
