# Generated by Django 5.2.6 on 2025-09-30 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0017_fotovehiculo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FotoVehiculo',
        ),
    ]
