# Generated by Django 5.2.6 on 2025-10-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0019_fotovehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='es_factura',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
