# Generated by Django 5.2.6 on 2025-10-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0020_factura_es_factura_alter_cliente_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='pagado_con_tarjeta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='es_tpv',
            field=models.BooleanField(default=False),
        ),
    ]
