# Generated by Django 5.2.6 on 2025-10-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0021_gasto_pagado_con_tarjeta_ingreso_es_tpv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='categoria',
            field=models.CharField(choices=[('Repuestos', 'Repuestos'), ('Sueldos', 'Sueldos'), ('Herramientas', 'Herramientas'), ('Suministros', 'Suministros'), ('Gasolina/Diesel', 'Gasolina/Diesel'), ('Otros', 'Otros'), ('Compra de Consumibles', 'Compra de Consumibles')], max_length=30),
        ),
    ]
