# Generated by Django 5.2.6 on 2025-10-25 18:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0022_alter_gasto_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula_nueva', models.CharField(blank=True, help_text='Matrícula si es un vehículo nuevo.', max_length=20, null=True)),
                ('marca_nueva', models.CharField(blank=True, help_text='Marca si es un vehículo nuevo.', max_length=50, null=True)),
                ('modelo_nuevo', models.CharField(blank=True, help_text='Modelo si es un vehículo nuevo.', max_length=50, null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('problema_o_trabajo', models.TextField(help_text='Descripción del problema o trabajo a presupuestar.')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptado', 'Aceptado'), ('Rechazado', 'Rechazado'), ('Convertido', 'Convertido a Orden')], default='Pendiente', max_length=20)),
                ('total_estimado', models.DecimalField(decimal_places=2, default=0.0, help_text='Cálculo total del presupuesto.', max_digits=10)),
                ('cliente', models.ForeignKey(help_text='Cliente al que se dirige el presupuesto.', on_delete=django.db.models.deletion.CASCADE, to='taller.cliente')),
                ('orden_asociada', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presupuesto_origen', to='taller.ordendereparacion')),
                ('vehiculo', models.ForeignKey(blank=True, help_text='Vehículo asociado (opcional, si ya existe).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='taller.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='LineaPresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Repuesto', 'Repuesto'), ('Consumible', 'Consumible'), ('Externo', 'Trabajo Externo'), ('Mano de Obra', 'Mano de Obra')], max_length=20)),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('precio_unitario_estimado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='taller.presupuesto')),
            ],
        ),
    ]
