# Generated by Django 5.2.6 on 2025-10-25 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0023_presupuesto_lineapresupuesto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presupuesto',
            name='orden_asociada',
        ),
        migrations.AddField(
            model_name='ordendereparacion',
            name='presupuesto_origen',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orden_generada', to='taller.presupuesto'),
        ),
    ]
