# Generated by Django 5.2.6 on 2025-10-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0024_remove_presupuesto_orden_asociada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoconsumible',
            name='nivel_minimo_stock',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Nivel mínimo para alerta (ej: 5.00). Dejar vacío si no se requiere alerta.', max_digits=10, null=True),
        ),
    ]
