# Generated by Django 5.2.6 on 2025-10-28 15:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0025_tipoconsumible_nivel_minimo_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoConsumibleStock',
            fields=[
            ],
            options={
                'verbose_name': 'Stock de Consumible',
                'verbose_name_plural': 'Stocks de Consumibles',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('taller.tipoconsumible',),
        ),
        migrations.CreateModel(
            name='AjusteStockConsumible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_ajustada', models.DecimalField(decimal_places=2, help_text='Cantidad a añadir (positivo) o quitar (negativo) del stock.', max_digits=10)),
                ('motivo', models.CharField(help_text='Razón del ajuste (Ej: Uso interno, Inventario físico, Pérdida)', max_length=255)),
                ('fecha_ajuste', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha del Ajuste')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.tipoconsumible', verbose_name='Tipo de Consumible')),
            ],
            options={
                'verbose_name': 'Ajuste de Stock',
                'verbose_name_plural': 'Ajustes de Stock',
                'ordering': ['-fecha_ajuste', '-id'],
            },
        ),
    ]
