# Generated by Django 5.2.6 on 2025-11-02 14:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0026_tipoconsumiblestock_ajustestockconsumible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='usoconsumible',
            name='fecha_uso',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
