# Generated by Django 5.2.6 on 2025-11-03 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0027_alter_gasto_fecha_alter_ingreso_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='notas_cliente',
            field=models.TextField(blank=True, help_text='Notas adicionales para el cliente', null=True),
        ),
    ]
