# Generated by Django 5.2.6 on 2025-11-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0028_factura_notas_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ciudad_fiscal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='codigo_postal_fiscal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion_fiscal',
            field=models.CharField(blank=True, help_text='Calle, Número, Piso, Puerta', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='documento_fiscal',
            field=models.CharField(blank=True, help_text='Número de DNI, NIE o NIF', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='provincia_fiscal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('DNI', 'DNI'), ('NIE', 'NIE'), ('NIF', 'NIF (Empresas)')], default='DNI', max_length=10, null=True),
        ),
    ]
