# Generated by Django 5.2.6 on 2025-11-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0029_cliente_ciudad_fiscal_cliente_codigo_postal_fiscal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='numero_factura',
            field=models.IntegerField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
