# Generated by Django 5.2.6 on 2025-11-20 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0030_factura_numero_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='aplicar_iva',
            field=models.BooleanField(default=True, help_text='Si marcado, se aplica el 21% de IVA y se muestran datos fiscales.'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ajustestockconsumible',
            name='cantidad_ajustada',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ajustestockconsumible',
            name='motivo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.cliente'),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='marca_nueva',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='matricula_nueva',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='modelo_nuevo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='problema_o_trabajo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='total_estimado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taller.vehiculo'),
        ),
        migrations.AlterField(
            model_name='tipoconsumible',
            name='nivel_minimo_stock',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
