# Generated by Django 5.2.6 on 2025-11-23 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0031_presupuesto_aplicar_iva_presupuesto_iva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo (Caja)'), ('CUENTA_ERIKA', 'Cuenta Erika (Compartida)'), ('CUENTA_TALLER', 'Cuenta Taller (Nueva)')], default='EFECTIVO', max_length=20),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo (Caja)'), ('CUENTA_ERIKA', 'Cuenta Erika (Compartida)'), ('CUENTA_TALLER', 'Cuenta Taller (Nueva)')], default='EFECTIVO', max_length=20),
        ),
    ]
