# Generated by Django 5.2.6 on 2025-11-30 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0032_gasto_metodo_pago_ingreso_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='orden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos', to='taller.ordendereparacion'),
        ),
    ]
