# Generated by Django 5.2.6 on 2026-02-19 19:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0033_gasto_orden'),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreTarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cierre', models.DateField(default=django.utils.timezone.now)),
                ('tarjeta', models.CharField(choices=[('TARJETA_1', 'Tarjeta 1 (Visa 2000€)'), ('TARJETA_2', 'Tarjeta 2 (Visa 1000€)')], max_length=20)),
                ('pago_cuota', models.DecimalField(decimal_places=2, help_text='Los 150€ o el pago total', max_digits=10)),
                ('saldo_deuda_banco', models.DecimalField(decimal_places=2, help_text='Deuda real que dice el banco', max_digits=10)),
                ('intereses_calculados', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.AlterModelOptions(
            name='ajustestockconsumible',
            options={'ordering': ['-fecha_ajuste', '-id']},
        ),
        migrations.AlterField(
            model_name='ajustestockconsumible',
            name='fecha_ajuste',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ajustestockconsumible',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.tipoconsumible'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='categoria',
            field=models.CharField(choices=[('Repuestos', 'Repuestos'), ('Sueldos', 'Sueldos'), ('Herramientas', 'Herramientas'), ('Suministros', 'Suministros'), ('Gasolina/Diesel', 'Gasolina/Diesel'), ('Otros', 'Otros'), ('Compra de Consumibles', 'Compra de Consumibles'), ('COMISIONES_INTERESES', 'Comisiones e Intereses Bancarios')], max_length=30),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo (Caja)'), ('CUENTA_TALLER', 'Cuenta Taller (Banco)'), ('TARJETA_1', 'Tarjeta 1 (Visa 2000€)'), ('TARJETA_2', 'Tarjeta 2 (Visa 1000€)'), ('CUENTA_ERIKA', 'Cuenta Erika (Antigua)')], default='EFECTIVO', max_length=20),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='categoria',
            field=models.CharField(choices=[('Taller', 'Pago de Cliente (Taller)'), ('Grua', 'Servicio de Grúa'), ('Otras Ganancias', 'Otras Ganancias'), ('ABONO_TARJETA', 'Abono/Pago a Tarjeta'), ('Otros', 'Otros Ingresos')], max_length=30),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo (Caja)'), ('CUENTA_TALLER', 'Cuenta Taller (Banco)'), ('TARJETA_1', 'Tarjeta 1 (Visa 2000€)'), ('TARJETA_2', 'Tarjeta 2 (Visa 1000€)'), ('CUENTA_ERIKA', 'Cuenta Erika (Antigua)')], default='EFECTIVO', max_length=20),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='aplicar_iva',
            field=models.BooleanField(default=True),
        ),
    ]
