# Generated by Django 5.2.6 on 2026-02-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0035_notatablon'),
    ]

    operations = [
        migrations.AddField(
            model_name='notatablon',
            name='completada',
            field=models.BooleanField(default=False),
        ),
    ]
