# Generated by Django 5.2.6 on 2026-02-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0037_notainternaorden'),
    ]

    operations = [
        migrations.AddField(
            model_name='notainternaorden',
            name='trabajo_interno',
            field=models.BooleanField(default=False, verbose_name='Vehículo del Taller'),
        ),
    ]
