# Generated by Django 5.2.6 on 2026-02-28 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0038_notainternaorden_trabajo_interno'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendereparacion',
            name='trabajo_interno',
            field=models.BooleanField(default=False, verbose_name='Vehículo del Taller'),
        ),
        migrations.AlterField(
            model_name='ordendereparacion',
            name='estado',
            field=models.CharField(choices=[('Recibido', 'Recibido'), ('En Diagnostico', 'En Diagnóstico'), ('Esperando Piezas', 'Esperando Piezas'), ('En Reparacion', 'En Reparación'), ('Listo para Recoger', 'Listo para Recoger'), ('Entregado', 'Entregado')], default='Recibido', max_length=50),
        ),
        migrations.AlterField(
            model_name='ordendereparacion',
            name='presupuesto_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taller.presupuesto'),
        ),
    ]
