# Generated by Django 5.2.6 on 2026-03-03 15:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0039_ordendereparacion_trabajo_interno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeudaTaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acreedor', models.CharField(help_text='A quién se le debe (Ej: Hermano, Cliente X)', max_length=150)),
                ('motivo', models.CharField(max_length=255)),
                ('importe_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_creacion', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='notainternaorden',
            name='trabajo_interno',
        ),
        migrations.AlterField(
            model_name='gasto',
            name='categoria',
            field=models.CharField(choices=[('Repuestos', 'Repuestos'), ('Sueldos', 'Sueldos'), ('Herramientas', 'Herramientas'), ('Suministros', 'Suministros'), ('Gasolina/Diesel', 'Gasolina/Diesel'), ('Otros', 'Otros'), ('Compra de Consumibles', 'Compra de Consumibles'), ('COMISIONES_INTERESES', 'Comisiones e Intereses Bancarios'), ('Pago de Deuda', 'Pago de Deuda (Taller)')], max_length=30),
        ),
        migrations.AddField(
            model_name='gasto',
            name='deuda_asociada',
            field=models.ForeignKey(blank=True, help_text='Si es un pago de deuda, elige a quién se le paga', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_pagados', to='taller.deudataller'),
        ),
    ]
