# Generated by Django 5.2.6 on 2026-03-03 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0040_deudataller_remove_notainternaorden_trabajo_interno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoconsumible',
            name='precio_coste_medio',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='Se calcula automáticamente con cada compra', max_digits=10),
        ),
        migrations.AlterField(
            model_name='ajustestockconsumible',
            name='cantidad_ajustada',
            field=models.DecimalField(decimal_places=2, help_text='Usa negativo para restar (Ej: -5) y positivo para sumar (Ej: 5)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='categoria',
            field=models.CharField(choices=[('Repuestos', 'Repuestos'), ('Sueldos', 'Sueldos'), ('Herramientas', 'Herramientas'), ('Suministros', 'Suministros (Agua, Café, etc.)'), ('Gasolina/Diesel', 'Gasolina/Diesel'), ('Otros', 'Otros'), ('Compra de Consumibles', 'Compra de Consumibles (Stock Taller)'), ('COMISIONES_INTERESES', 'Comisiones e Intereses Bancarios'), ('Pago de Deuda', 'Pago de Deuda (Taller)')], max_length=30),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='deuda_asociada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_pagados', to='taller.deudataller'),
        ),
    ]
