# Generated by Django 5.2.6 on 2026-03-03 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0041_tipoconsumible_precio_coste_medio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deudataller',
            name='orden',
            field=models.ForeignKey(blank=True, help_text='Orden de trabajo asociada', null=True, on_delete=django.db.models.deletion.SET_NULL, to='taller.ordendereparacion'),
        ),
    ]
