# Generated by Django 5.2.6 on 2026-03-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0042_deudataller_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo (Caja)'), ('CUENTA_TALLER', 'Cuenta Taller (Banco)'), ('TARJETA_1', 'Tarjeta 1 (Visa 2000€)'), ('TARJETA_2', 'Tarjeta 2 (Visa 1000€)'), ('CUENTA_ERIKA', 'Cuenta Erika (Antigua)'), ('COMPENSACION', 'Compensación (Trueque / Sin dinero)')], default='EFECTIVO', max_length=20),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo (Caja)'), ('CUENTA_TALLER', 'Cuenta Taller (Banco)'), ('TARJETA_1', 'Tarjeta 1 (Visa 2000€)'), ('TARJETA_2', 'Tarjeta 2 (Visa 1000€)'), ('CUENTA_ERIKA', 'Cuenta Erika (Antigua)'), ('COMPENSACION', 'Compensación (Trueque / Sin dinero)')], default='EFECTIVO', max_length=20),
        ),
    ]
