# Generated by Django 5.2.6 on 2026-03-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0044_alter_gasto_metodo_pago_alter_ingreso_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='notainternaorden',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='notas_internas/'),
        ),
    ]
