# Generated by Django 5.2.6 on 2026-03-04 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0045_notainternaorden_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmpliacionDeuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motivo', models.CharField(max_length=255)),
                ('deuda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ampliaciones', to='taller.deudataller')),
            ],
        ),
    ]
