# Generated by Django 5.2.6 on 2026-03-04 20:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0046_ampliaciondeuda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineafactura',
            name='tipo',
            field=models.CharField(choices=[('Repuesto', 'Repuesto'), ('Consumible', 'Consumible'), ('Externo', 'Trabajo Externo'), ('Mano de Obra', 'Mano de Obra'), ('Grúa', 'Servicio de Grúa')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lineapresupuesto',
            name='tipo',
            field=models.CharField(choices=[('Repuesto', 'Repuesto'), ('Consumible', 'Consumible'), ('Externo', 'Trabajo Externo'), ('Mano de Obra', 'Mano de Obra'), ('Grúa', 'Servicio de Grúa')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ordendereparacion',
            name='estado',
            field=models.CharField(choices=[('Recibido', 'Recibido'), ('En Diagnostico', 'En Diagnóstico'), ('Esperando Autorizacion', 'Esperando Autorización'), ('Esperando Piezas', 'Esperando Piezas'), ('En Reparacion', 'En Reparación'), ('En Pruebas', 'En Pruebas'), ('Listo para Recoger', 'Listo para Recoger'), ('Entregado', 'Entregado')], default='Recibido', max_length=50),
        ),
        migrations.CreateModel(
            name='HistorialEstadoOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='taller.ordendereparacion')),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
