# Generated by Django 5.2.6 on 2026-03-08 19:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0048_historialestadoorden_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordendereparacion',
            name='fecha_entrada',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
