# Generated by Django 5.2.6 on 2026-03-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0049_alter_ordendereparacion_fecha_entrada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=150, verbose_name='Nombre del Cliente')),
                ('vehiculo_info', models.CharField(blank=True, max_length=150, null=True, verbose_name='Vehículo / Matrícula')),
                ('motivo', models.CharField(max_length=255, verbose_name='Motivo de la cita (Reparación)')),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y Hora de la cita')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En taller', 'Ya está en el taller'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=20)),
                ('notas_adicionales', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['fecha_hora'],
            },
        ),
    ]
