# Generated by Django 5.2.6 on 2026-03-09 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0050_cita'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='presupuesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taller.presupuesto', verbose_name='Presupuesto Asociado'),
        ),
    ]
