# Generated by Django 5.2.6 on 2026-03-09 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0051_cita_presupuesto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peticion', models.TextField(verbose_name='Lo que pediste')),
                ('respuesta', models.TextField(verbose_name='Lo que contestó J.A.R.V.I.S.')),
                ('accion_ejecutada', models.CharField(blank=True, max_length=100, null=True, verbose_name='Acción interna')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historial de IA',
                'verbose_name_plural': 'Historiales de IA',
                'ordering': ['-fecha'],
            },
        ),
    ]
