# Generated by Django 5.2.6 on 2026-03-26 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0052_historialia'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso',
            name='deuda_asociada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taller.deudataller', verbose_name='¿Es un préstamo? Añadir a Deuda Existente'),
        ),
    ]
