# Generated by Django 5.2.6 on 2026-03-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0053_ingreso_deuda_asociada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='categoria',
            field=models.CharField(choices=[('Taller', 'Pago de Cliente (Taller)'), ('Grua', 'Servicio de Grúa'), ('Otras Ganancias', 'Otras Ganancias'), ('ABONO_TARJETA', 'Abono/Pago a Tarjeta'), ('PRESTAMO', '🤝 Préstamo / Adelanto a Devolver'), ('Otros', 'Otros Ingresos')], max_length=30),
        ),
    ]
