# Generated by Django 5.2.6 on 2026-03-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0054_alter_ingreso_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='deudataller',
            name='es_credito_bancario',
            field=models.BooleanField(default=False, help_text='Si se marca, al pagar calculará automáticamente los intereses comparando con el saldo del banco.'),
        ),
    ]
