# Generated by Django 5.2.6 on 2026-03-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0056_alter_gasto_metodo_pago_alter_ingreso_metodo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='categoria',
            field=models.CharField(choices=[('Repuestos', 'Repuestos'), ('Sueldos', 'Sueldos'), ('Herramientas', 'Herramientas'), ('Suministros', 'Suministros (Agua, Café, etc.)'), ('Gasolina/Diesel', 'Gasolina/Diesel'), ('Otros', 'Otros'), ('Compra de Consumibles', 'Compra de Consumibles (Stock Taller)'), ('COMISIONES_INTERESES', 'Comisiones e Intereses Bancarios'), ('Pago de Deuda', 'Pago de Deuda (Taller)'), ('PAGO_TARJETA', '💳 Pago de Tarjeta de Crédito')], max_length=30),
        ),
    ]
