# Generated by Django 5.2.6 on 2026-03-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0057_alter_gasto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendereparacion',
            name='danos_previos',
            field=models.TextField(blank=True, null=True, verbose_name='Daños Previos (Rayones, golpes...)'),
        ),
    ]
