# Generated by Django 5.2.6 on 2026-03-29 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0058_ordendereparacion_danos_previos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteEscaner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_pdf', models.FileField(upload_to='reportes_escaner/', verbose_name='Archivo PDF del Escáner')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.CharField(default='Reporte de Diagnóstico Automático', max_length=255)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_escaner', to='taller.ordendereparacion')),
            ],
        ),
    ]
