# Generated by Django 5.2.6 on 2026-03-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0059_reporteescaner'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporteescaner',
            name='enlace_web',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Enlace del Escáner'),
        ),
        migrations.AlterField(
            model_name='reporteescaner',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='reportes_escaner/', verbose_name='Archivo PDF del Escáner'),
        ),
    ]
