# Generated by Django 5.2.6 on 2026-03-31 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0060_reporteescaner_enlace_web_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialestadoorden',
            name='es_pausa_jornada',
            field=models.BooleanField(default=False),
        ),
    ]
