# Generated by Django 5.2.6 on 2026-04-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0062_empleado_sueldo_por_dia_empleado_telefono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notainternaorden',
            name='visible_cliente',
            field=models.BooleanField(default=False),
        ),
    ]
