# Generated by Django 5.2.6 on 2026-04-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0063_notainternaorden_visible_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='es_sueldo_fijo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empleado',
            name='sueldo_fijo_mensual',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=8),
        ),
    ]
