# Generated by Django 5.2.6 on 2026-04-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0064_empleado_es_sueldo_fijo_empleado_sueldo_fijo_mensual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo (Caja)'), ('CUENTA_TALLER', 'Cuenta Taller (Banco)'), ('TARJETA_1', 'Tarjeta 1 (Visa 2000€)'), ('TARJETA_2', 'Tarjeta 2 (Visa 1000€)'), ('COMPENSACION', '🤝 Compensación (Trueque / Sin dinero)'), ('FIADO', '📝 Dejado a Deber / Fiado (Genera Deuda)')], default='EFECTIVO', max_length=20),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo (Caja)'), ('CUENTA_TALLER', 'Cuenta Taller (Banco)'), ('TARJETA_1', 'Tarjeta 1 (Visa 2000€)'), ('TARJETA_2', 'Tarjeta 2 (Visa 1000€)'), ('COMPENSACION', '🤝 Compensación (Trueque / Sin dinero)'), ('FIADO', '📝 Dejado a Deber / Fiado (Genera Deuda)')], default='EFECTIVO', max_length=20),
        ),
    ]
