# Generated by Django 5.2.6 on 2026-04-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0065_alter_gasto_metodo_pago_alter_ingreso_metodo_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='facturas_proveedores/')),
                ('fecha_factura', models.DateField(verbose_name='Fecha de la Factura')),
                ('proveedor', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del Proveedor')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
