# Generated by Django 5.2.6 on 2026-04-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0066_facturaproveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaproveedor',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='IVA Pagado'),
        ),
    ]
