# Generated by Django 5.2.6 on 2026-04-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0067_facturaproveedor_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendereparacion',
            name='kilometraje_recepcion',
            field=models.IntegerField(default=0, verbose_name='Kilómetros al entrar'),
        ),
    ]
