# Generated by Django 5.2.6 on 2026-04-16 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0068_ordendereparacion_kilometraje_recepcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='tipo_jornada',
            field=models.CharField(choices=[('Taller', 'Taller / Estructuras (Cobra el día)'), ('Chapa', 'Chapa y Pintura (Solo cobra comisiones)')], default='Taller', max_length=20),
        ),
        migrations.AddField(
            model_name='empleado',
            name='es_chapista',
            field=models.BooleanField(default=False, verbose_name='Trabaja a Comisión (Ej: Chapa y Pintura)'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='porcentaje_comision',
            field=models.DecimalField(decimal_places=2, default=60.0, max_digits=5, verbose_name='Porcentaje de Comisión (%)'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='valor_jornada_taller',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10, verbose_name='Valor Día (Trabajo Interno/Taller)'),
        ),
        migrations.AddField(
            model_name='lineafactura',
            name='mecanico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taller.empleado', verbose_name='Mecánico Asignado (Comisión)'),
        ),
    ]
