# Generated by Django 5.2.6 on 2026-04-21 17:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0069_asistencia_tipo_jornada_empleado_es_chapista_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='categoria',
            field=models.CharField(choices=[('Repuestos', 'Repuestos'), ('Sueldos', 'Sueldos'), ('Herramientas', 'Herramientas'), ('Suministros', 'Suministros (Agua, Café, etc.)'), ('Gasolina/Diesel', 'Gasolina/Diesel'), ('Otros', 'Otros'), ('Compra de Consumibles', 'Compra de Consumibles (Stock Taller)'), ('COMISIONES_INTERESES', 'Comisiones e Intereses Bancarios'), ('Pago de Deuda', 'Pago de Deuda (Taller)'), ('PAGO_TARJETA', '💳 Pago de Tarjeta de Crédito'), ('MATERIAL_CHAPA', '🎨 Material Chapa y Pintura')], max_length=30),
        ),
        migrations.CreateModel(
            name='StockMaterialChapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Ej: Pintura Blanca UHS, Barniz, Masilla...', max_length=255)),
                ('importe_total', models.DecimalField(decimal_places=2, help_text='Lo que costó el bote o lote completo', max_digits=10)),
                ('fecha_registro', models.DateField(default=django.utils.timezone.now)),
                ('gasto_original', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lote_chapa', to='taller.gasto')),
            ],
        ),
        migrations.CreateModel(
            name='UsoMaterialChapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe_usado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_uso', models.DateField(default=django.utils.timezone.now)),
                ('notas', models.CharField(blank=True, help_text='Ej: Pintado de aleta y capó', max_length=255, null=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos', to='taller.stockmaterialchapa')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales_chapa_usados', to='taller.ordendereparacion')),
            ],
        ),
    ]
