# Generated by Django 5.2.6 on 2026-05-14 15:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0070_alter_gasto_categoria_stockmaterialchapa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='sueldo_ganado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Sueldo del día'),
        ),
        migrations.CreateModel(
            name='HistorialSueldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now, help_text='Fecha a partir de la cual entra en vigor este sueldo')),
                ('sueldo_por_dia', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('sueldo_fijo_mensual', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10)),
                ('valor_jornada_taller', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('porcentaje_comision', models.DecimalField(decimal_places=2, default=60.0, max_digits=5)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_sueldos', to='taller.empleado')),
            ],
            options={
                'verbose_name': 'Historial de Sueldo',
                'verbose_name_plural': 'Historiales de Sueldos',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
